[package]
name = "mlfq-panic"
version = "0.1.0"
edition = "2021"

[package.metadata.verus]
verify = true

[dependencies]
rand = "0.9.0"
vstd = { git = "https://github.com/verus-lang/verus.git", rev="a53f39271666ac7dc9f455b6267da4c49a5f75c6" }
