[package]
name = "toy-bounds-check"
version = "0.1.0"
edition = "2024"

[package.metadata.flux]
enabled = true

[dependencies]
flux-rs = { git = "https://github.com/flux-rs/flux.git" }
rvec = { path = "../rvec" }
